FROM buildpack-deps:jessie
MAINTAINER Vladislav K. Synkov <vladsynkov@gmail.com>

# Install packages for building ruby
RUN apt-get update \
    && apt-get install -y --force-yes git nodejs postgresql-client sqlite3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV RUBY_VERSION 2.2.3
RUN git clone https://github.com/sstephenson/ruby-build.git && cd ruby-build && ./install.sh
RUN echo 'gem: --no-rdoc --no-ri' >> "$HOME/.gemrc"

# Install ruby
RUN ruby-build $RUBY_VERSION /usr/local
RUN gem install bundler

ADD . /usr/src/app
WORKDIR /usr/src/app

# throw errors if Gemfile has been modified since Gemfile.lock
# RUN bundle config --global frozen 1
RUN bundle install
RUN bundle exec rake assets:precompile

ENV RAILS_ENV production

# EXPOSE 3000
# CMD ["rails", "server", "-b", "0.0.0.0"]

